version: '3.2'

services:
  fly:
    build:
      context: fly/
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - elasticsearch
    extra_hosts:
      elasticsearch: 127.0.0.1
