ARG ELK_VERSION

# https://github.com/elastic/apm-server/blob/master/apm-server.docker.yml
FROM docker.elastic.co/apm/apm-server:${ELK_VERSION}

# Add your apm plugins setup here
# Example: RUN apm-plugin install analysis-icu
